version: '3'
services:
  frontend:
    image: eunhomoon/docker-frontend
    volumes:
      - /app/node_modeuls
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m
    platform: linux/amd64

  nginx:
    restart: always
    image: eunhomoon/docker-nginx
    ports:
      - '80:80'
    mem_limit: 128m
    links:
      - frontend
      - backend
    platform: linux/amd64

  backend:
    image: eunhomoon/docker-backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      MYSQL_HOST: docker-mysql-instance-1.cr3d7ewbbf0v.ap-northeast-2.rds.amazonaws.com
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: myapp
      MYSQL_PORT: 3306
    mem_limit: 128m
    platform: linux/amd64

  # mysql:
  #   build: ./mysql
  #   restart: unless-stopped
  #   container_name: app_mysql
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 1234
  #     MYSQL_DATABASE: myapp
