name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    
    - uses: docker/setup-buildx-action@v1
    - name: Build the Docker image
#       run: 
#         docker build -t eunhomoon/fullstack-frontend ./frontend eunhomoon/fullstack-backend ./backend eunhomoon/fullstack-nginx ./nginx
