name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  IMAGE_NAME: eunhomoon/docker-fullstack
  DOCKERFILE_PATHS: |
    ./backend/Dockerfile
    ./frontend/Dockerfile

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        file: ${{fromYaml(env.DOCKERFILE_PATHS)}}

    steps:
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      uses: docker/build-push-actions@v2
      with:
        context: ./
        dockerfile: ${{ matrix.file }}
        push: false
        tags: ${{ env.IMAGE_NAME }}:${{ matrix:file }}
