name: Docker Compose Build

on:
  push:
    branches:
      - main  # 또는 빌드를 트리거할 브랜치

jobs:
  build:
    runs-on: ubuntu-latest  # 실행 환경 선택

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # 저장소 체크아웃

    - name: Set up Docker Compose
      uses: docker/compose-cli@v1  # Docker Compose 설치

    - name: Build and Push Docker Images
      run: |
        export DOCKER_BUILDKIT=1
        docker compose build
