name: Build and Push Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          docker build -t eunhomoon/docker-frontend ./frontend
          docker build -t eunhomoon/docker-backend ./backend
          docker build -t eunhomoon/docker-nginx ./nginx

      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker images
        run: |
          docker push eunhomoon/docker-frontend
          docker push eunhomoon/docker-nginx
          docker push eunhomoon/docker-backend
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
        
      - name: Install and configure EB CLI
        run: |
          pip install awsebcli --upgrade --user
          echo 'export PATH="$PATH:$HOME/.local/bin"' >> $GITHUB_ENV

      - name: Deploy to Elastic Beanstalk
        run: |
          eb init -p docker docker-fullstack-app --region ap-northeast-2
          eb use Docker-fullstack-app-env
          
#       - name: Install and configure AWS CLI
#         run: |
#           sudo apt-get install -y python3-pip
#           sudo pip3 install awsebcli --upgrade

#       - name: Copy Docker Compose file
#         run: mv docker-compose.yml docker-compose.yml
#         #  cp ./docker-compose.yml .
          

#       - name: Deploy to Elastic Beanstalk
#         run: eb deploy

