name: Build and Push Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          docker build -t eunhomoon/docker-frontend ./frontend
          docker build -t eunhomoon/docker-backend ./backend
          docker build -t eunhomoon/docker-nginx ./nginx

      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker images
        run: |
          docker push eunhomoon/docker-frontend
          docker push eunhomoon/docker-nginx
          docker push eunhomoon/docker-backend
